---
- name: Validate Nginx configuration before reload
  ansible.builtin.command:
    cmd: nginx -t
  changed_when: false
  listen: Reload Nginx (systemd)

- name: Reload Nginx (systemd)
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
  when: not ansible_check_mode
  listen: Reload Nginx (systemd)

- name: Restart Panel Stack
  community.docker.docker_compose_v2:
    project_src: "{{ remnawave_panel_root_dir }}"
    state: present
    pull: missing
    recreate: always
    remove_orphans: true

- name: Restart Subscription Page
  community.docker.docker_compose_v2:
    project_src: "{{ remnawave_sub_dir }}"
    services:
      - "{{ remnawave_sub_container_name | default('remnawave-subscription-page') }}"
    state: present
    pull: missing
    recreate: always
